AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This is a sample template with a multi line string description

Parameters:
  VpcCidr:
    Type: String
    Default: "10.0.0.0/16"
    Description: the VPC cidr block
    AllowedPattern: ^([0-9]{1,3}\.){3}([0-9]{1,3})\/[0-9]{1,2}$

Resources:
  MasterVpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MasterVpc

  MasterInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: keyname
          Value: value
  MasterInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref MasterVpc
      InternetGatewayId: !Ref MasterInternetGateway

  MasterSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select
        - 0
        - Fn::GetAZs: !Ref "AWS::Region"
      VpcId: !Ref MasterVpc
      CidrBlock: !Select [1, !Cidr [!Ref VpcCidr, 2, 8]]
      Tags:
        - Key: Name
          Value: MasterVpc-Subnet1
